name: SkyFlow Build & Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore application
        run: dotnet restore SkyFlow/SkyFlow.csproj

      - name: Restore tests
        run: dotnet restore SkyFlow.Tests/SkyFlow.Tests.csproj

      - name: Build application
        run: dotnet build SkyFlow/SkyFlow.csproj --configuration Release --no-restore

      - name: Run automated tests
        run: dotnet test SkyFlow.Tests/SkyFlow.Tests.csproj --configuration Release --no-restore --verbosity normal